Front Page
ncs-jss/Code-Pad pull request #21
Opened 2018-06-25 16:12 UTC by anantjain6

Patch #19

2018-07-02 14:57 UTC, anantjain6 commented
@ankitjain28may Sir, plz review

2018-07-02 17:12 UTC, ankitjain28may requested changes
You have removed the extra code, I haven't checked it by running locally, Will check soon. Try to add some code like displaying latest events going on.

2018-07-02 17:12 UTC, ankitjain28may commented on resources/views/dashboard.blade.php
> +                <p>Our system will test your code with verious test case with all the possiblities.</p>
typos 'various test cases' and possibilities

2018-07-02 17:12 UTC, ankitjain28may commented on resources/views/dashboard.blade.php
> +                <h3>Compet</h3>
Typo error Compete

2018-12-08 14:39 UTC, ankitjain28may commented
No activity since last review, Closing this.

2018-12-08 14:39 UTC, closed without merging